#!/usr/bin/env node
// Generates the diagram and the link index for each view in views/.
//
//   node tools/build-views.mjs [root]            rewrite every view
//   node tools/build-views.mjs [root] --check    report stale views, write nothing
//
// A view is a definition, not a picture: its frontmatter says which entries
// to start from and which relationships to follow, and everything below the
// generated marker is derived from the records. Editing that part by hand is
// a change the next run silently reverts, so tools/check.mjs treats a view
// whose block disagrees with its records as a finding.
//
// Diagram nodes are deliberately not links. GitHub renders Mermaid in a
// sandboxed frame that its own CSP stops navigating, and a committed SVG is
// framed from another domain rather than inlined, so no framework buys
// clickable nodes there. The index below the diagram is the navigation, in
// ordinary markdown links that work everywhere the file is read.

import { writeFileSync } from 'node:fs';
import { join, resolve, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectEntries, typedRefs, TYPED_REF, KIND_PATH, EDGE_LABELS } from './collection.mjs';

export const MARKER = '<!-- generated by tools/build-views.mjs: everything below is derived from the records -->';

// The order kinds are drawn and listed in: the entrypoint first, then what
// supports it, then what it is run against, then what it rests on.
const KIND_ORDER = ['mission', 'founder', 'skill', 'knowledge', 'case', 'evidence'];
const KIND_HEADING = { mission: 'Missions', founder: 'Founder context', skill: 'Skills', knowledge: 'Knowledge', case: 'Cases', evidence: 'Evidence' };
// Shape, not colour. Kinds are told apart by outline so the map stays
// readable in both GitHub themes and leaves palette choices unmade.
const KIND_SHAPE = {
  mission: (label) => `(["${label}"])`,
  founder: (label) => `[["${label}"]]`,
  skill: (label) => `[["${label}"]]`,
  knowledge: (label) => `["${label}"]`,
  case: (label) => `{{"${label}"}}`,
  evidence: (label) => `[("${label}")]`,
};
const DEFAULT_DEPTH = 2;

const titleOf = (entry) => String(entry.data?.title ?? entry.data?.source_title ?? entry.data?.name ?? entry.id);
const nodeId = (token) => token.replace(/[:-]/g, '_');
// Mermaid reads a quote inside a quoted label as the end of it.
const mermaidLabel = (text) => text.replace(/"/g, '#quot;').replace(/\s+/g, ' ').trim();

// Every typed ref between two entries, as an undirected adjacency map with
// the direction and label kept for drawing. Traversal has to be undirected:
// a knowledge entry records `applies_to` pointing at a skill, so a view that
// starts from the skill would otherwise reach nothing.
function buildGraph(entries) {
  const byToken = new Map(entries.map((e) => [e.token, e]));
  const edges = [];
  for (const entry of entries) {
    if (entry.kind === 'view') continue;
    for (const { ref, label } of typedRefs(entry.data)) {
      const m = TYPED_REF.exec(String(ref));
      if (!m || m[1] === 'view') continue;
      const to = `${m[1]}:${m[2]}`;
      if (!byToken.has(to) || !EDGE_LABELS.includes(label)) continue;
      edges.push({ from: entry.token, to, label });
    }
  }
  return { byToken, edges };
}

function select(graph, view) {
  const definition = view.data?.view ?? {};
  const follow = Array.isArray(definition.follow) && definition.follow.length
    ? definition.follow.map(String)
    : EDGE_LABELS;
  const depth = definition.depth === undefined ? DEFAULT_DEPTH : Number(definition.depth);
  const seeds = (Array.isArray(definition.include) ? definition.include : [])
    .map(String).filter((token) => graph.byToken.has(token));

  const followed = new Map();
  for (const edge of graph.edges) {
    if (follow.includes(edge.label)) followed.set(`${edge.from} ${edge.label} ${edge.to}`, edge);
  }
  const reachable = new Map();
  const add = (a, b) => reachable.set(a, (reachable.get(a) ?? new Set()).add(b));
  for (const { from, to } of followed.values()) { add(from, to); add(to, from); }

  const nodes = new Set(seeds);
  let frontier = seeds;
  for (let step = 0; step < depth && frontier.length; step++) {
    const next = [];
    for (const token of frontier) {
      for (const neighbour of reachable.get(token) ?? []) {
        if (nodes.has(neighbour)) continue;
        nodes.add(neighbour);
        next.push(neighbour);
      }
    }
    frontier = next;
  }
  const inView = [...followed.values()].filter((e) => nodes.has(e.from) && nodes.has(e.to));
  return { nodes: sortTokens([...nodes]), edges: sortEdges(inView) };
}

const rank = (token) => {
  const i = KIND_ORDER.indexOf(token.split(':')[0]);
  return `${i < 0 ? KIND_ORDER.length : i}${token}`;
};
const sortTokens = (tokens) => tokens.sort((a, b) => rank(a).localeCompare(rank(b)));
const sortEdges = (edges) => edges.sort((a, b) =>
  rank(a.from).localeCompare(rank(b.from)) || rank(a.to).localeCompare(rank(b.to)) || a.label.localeCompare(b.label));

// The link a reader follows, written from the view's own directory so it
// resolves the same in a clone, on GitHub, and in an editor.
function linkTo(root, view, token) {
  const at = token.indexOf(':');
  const target = join(root, KIND_PATH[token.slice(0, at)](token.slice(at + 1)));
  return relative(dirname(view.path), target).split(sep).join('/');
}

// Returns the text of the generated block and the tokens it names, so a
// caller can check the view's links against exactly what it drew.
export function renderView(root, entries, view) {
  const graph = buildGraph(entries);
  const { nodes, edges } = select(graph, view);
  const lines = [MARKER, '', '```mermaid', 'flowchart LR'];

  for (const token of nodes) {
    const entry = graph.byToken.get(token);
    lines.push(`  ${nodeId(token)}${KIND_SHAPE[entry.kind](mermaidLabel(titleOf(entry)))}`);
  }
  if (edges.length) lines.push('');
  for (const { from, to, label } of edges) {
    lines.push(`  ${nodeId(from)} -->|${label}| ${nodeId(to)}`);
  }
  lines.push('```', '');

  lines.push('## What is in this view', '');
  if (nodes.length === 0) {
    lines.push('Nothing: no entry in this collection matches the selection above.', '');
  }
  for (const kind of KIND_ORDER) {
    const of = nodes.filter((token) => token.startsWith(`${kind}:`));
    if (!of.length) continue;
    lines.push(`### ${KIND_HEADING[kind]}`, '');
    for (const token of of) {
      lines.push(`- [${titleOf(graph.byToken.get(token))}](${linkTo(root, view, token)}), \`${token}\``);
    }
    lines.push('');
  }
  return { text: lines.join('\n').replace(/\n+$/, '\n'), nodes };
}

// The hand-written half of a view is everything above the marker; the
// generator never touches it.
export const definitionOf = (text) => {
  const at = text.indexOf(MARKER);
  return at < 0 ? null : text.slice(0, at);
};

// A view with no marker yet is not an error the author has to repair by
// hand: the generator puts the marker after whatever they wrote and fills in
// below it. The checker still reports the committed file, so the remedy it
// names is one a contributor can actually run.
export function rebuild(root, entries, view) {
  const definition = definitionOf(view.text);
  const missing = definition === null;
  const { text, nodes } = renderView(root, entries, view);
  const wanted = (missing ? view.text.replace(/\n*$/, '\n\n') : definition) + text;
  return { missing, stale: missing || wanted !== view.text, text: wanted, nodes };
}

// -------------------------------------------------------------------- cli

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');
  const root = resolve(args.find((a) => !a.startsWith('--')) ?? join(dirname(fileURLToPath(import.meta.url)), '..'));
  const { entries } = collectEntries(root);
  const views = entries.filter((e) => e.kind === 'view' && e.data);

  let stale = 0;
  for (const view of views) {
    const result = rebuild(root, entries, view);
    if (!result.stale) { console.log(`ok     ${view.rel}: ${result.nodes.length} entries`); continue; }
    stale++;
    const why = result.missing
      ? 'it has no generated block yet'
      : 'the committed block is not what these records generate';
    if (checkOnly) { console.log(`STALE  ${view.rel}: ${why}`); continue; }
    writeFileSync(view.path, result.text);
    console.log(`wrote  ${view.rel}: ${result.nodes.length} entries, because ${why}`);
  }

  if (views.length === 0) console.log('no views to build');
  if (checkOnly && stale) {
    console.log(`\nRED    ${stale} view${stale === 1 ? '' : 's'} disagree with the records; run node tools/build-views.mjs`);
    process.exit(1);
  }
  const counted = `${views.length} view${views.length === 1 ? '' : 's'}`;
  console.log(`\nGREEN  ${counted} ${checkOnly ? 'up to date with the records' : 'generated'}`);
}
